# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarTrack-Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarTrack-Challenge
    pod 'RxSwift', '6.1.0'
    pod 'RxCocoa', '6.1.0'
    pod "RxRealm"
    pod 'Alamofire', '~> 5.2'
    pod 'NVActivityIndicatorView'

  target 'CarTrack-ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.1.0'
    pod 'RxTest', '6.1.0'
  end

  target 'CarTrack-ChallengeUITests' do
    # Pods for testing
  end

end
